# Generated by Django 4.2.5 on 2023-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_cars_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField()),
                ('cars_values', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
