# Generated by Django 4.2.5 on 2023-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carsinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
