# Generated by Django 4.2.5 on 2024-01-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_cars_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsinventory',
            name='cars_values',
            field=models.FloatField(null=True),
        ),
    ]
